package com.example.regservicebuilder.model.impl;

import com.example.regservicebuilder.model.District;
import com.example.regservicebuilder.model.DistrictModel;
import com.example.regservicebuilder.model.DistrictSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the District service. Represents a row in the &quot;Regs_District&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.example.regservicebuilder.model.DistrictModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistrictImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DistrictImpl
 * @see com.example.regservicebuilder.model.District
 * @see com.example.regservicebuilder.model.DistrictModel
 * @generated
 */
@JSON(strict = true)
public class DistrictModelImpl extends BaseModelImpl<District>
    implements DistrictModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a district model instance should use the {@link com.example.regservicebuilder.model.District} interface instead.
     */
    public static final String TABLE_NAME = "Regs_District";
    public static final Object[][] TABLE_COLUMNS = {
            { "districtId", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "code_", Types.VARCHAR },
            { "archived", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Regs_District (districtId LONG not null primary key,name VARCHAR(75) null,code_ VARCHAR(75) null,archived VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table Regs_District";
    public static final String ORDER_BY_JPQL = " ORDER BY district.districtId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Regs_District.districtId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.example.regservicebuilder.model.District"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.example.regservicebuilder.model.District"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.example.regservicebuilder.model.District"),
            true);
    public static long ARCHIVED_COLUMN_BITMASK = 1L;
    public static long DISTRICTID_COLUMN_BITMASK = 2L;
    public static final String MAPPING_TABLE_REGS_REGS_FARMER_DISTRICTS_NAME = "Regs_Regs_Farmer_Districts";
    public static final Object[][] MAPPING_TABLE_REGS_REGS_FARMER_DISTRICTS_COLUMNS =
        {
            { "districtId", Types.BIGINT },
            { "farmerId", Types.BIGINT }
        };
    public static final String MAPPING_TABLE_REGS_REGS_FARMER_DISTRICTS_SQL_CREATE =
        "create table Regs_Regs_Farmer_Districts (districtId LONG not null,farmerId LONG not null,primary key (districtId, farmerId))";
    public static final boolean FINDER_CACHE_ENABLED_REGS_REGS_FARMER_DISTRICTS = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.Regs_Regs_Farmer_Districts"),
            true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.example.regservicebuilder.model.District"));
    private static ClassLoader _classLoader = District.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            District.class
        };
    private long _districtId;
    private String _name;
    private String _code;
    private String _archived;
    private String _originalArchived;
    private long _columnBitmask;
    private District _escapedModel;

    public DistrictModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static District toModel(DistrictSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        District model = new DistrictImpl();

        model.setDistrictId(soapModel.getDistrictId());
        model.setName(soapModel.getName());
        model.setCode(soapModel.getCode());
        model.setArchived(soapModel.getArchived());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<District> toModels(DistrictSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<District> models = new ArrayList<District>(soapModels.length);

        for (DistrictSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _districtId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setDistrictId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _districtId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return District.class;
    }

    @Override
    public String getModelClassName() {
        return District.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("districtId", getDistrictId());
        attributes.put("name", getName());
        attributes.put("code", getCode());
        attributes.put("archived", getArchived());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long districtId = (Long) attributes.get("districtId");

        if (districtId != null) {
            setDistrictId(districtId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String code = (String) attributes.get("code");

        if (code != null) {
            setCode(code);
        }

        String archived = (String) attributes.get("archived");

        if (archived != null) {
            setArchived(archived);
        }
    }

    @JSON
    @Override
    public long getDistrictId() {
        return _districtId;
    }

    @Override
    public void setDistrictId(long districtId) {
        _districtId = districtId;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getCode() {
        if (_code == null) {
            return StringPool.BLANK;
        } else {
            return _code;
        }
    }

    @Override
    public void setCode(String code) {
        _code = code;
    }

    @JSON
    @Override
    public String getArchived() {
        if (_archived == null) {
            return StringPool.BLANK;
        } else {
            return _archived;
        }
    }

    @Override
    public void setArchived(String archived) {
        _columnBitmask |= ARCHIVED_COLUMN_BITMASK;

        if (_originalArchived == null) {
            _originalArchived = _archived;
        }

        _archived = archived;
    }

    public String getOriginalArchived() {
        return GetterUtil.getString(_originalArchived);
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            District.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public District toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (District) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        DistrictImpl districtImpl = new DistrictImpl();

        districtImpl.setDistrictId(getDistrictId());
        districtImpl.setName(getName());
        districtImpl.setCode(getCode());
        districtImpl.setArchived(getArchived());

        districtImpl.resetOriginalValues();

        return districtImpl;
    }

    @Override
    public int compareTo(District district) {
        long primaryKey = district.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof District)) {
            return false;
        }

        District district = (District) obj;

        long primaryKey = district.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        DistrictModelImpl districtModelImpl = this;

        districtModelImpl._originalArchived = districtModelImpl._archived;

        districtModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<District> toCacheModel() {
        DistrictCacheModel districtCacheModel = new DistrictCacheModel();

        districtCacheModel.districtId = getDistrictId();

        districtCacheModel.name = getName();

        String name = districtCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            districtCacheModel.name = null;
        }

        districtCacheModel.code = getCode();

        String code = districtCacheModel.code;

        if ((code != null) && (code.length() == 0)) {
            districtCacheModel.code = null;
        }

        districtCacheModel.archived = getArchived();

        String archived = districtCacheModel.archived;

        if ((archived != null) && (archived.length() == 0)) {
            districtCacheModel.archived = null;
        }

        return districtCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{districtId=");
        sb.append(getDistrictId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", code=");
        sb.append(getCode());
        sb.append(", archived=");
        sb.append(getArchived());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("com.example.regservicebuilder.model.District");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>districtId</column-name><column-value><![CDATA[");
        sb.append(getDistrictId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>code</column-name><column-value><![CDATA[");
        sb.append(getCode());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>archived</column-name><column-value><![CDATA[");
        sb.append(getArchived());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
