package com.example.regservicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Farmer service. Represents a row in the &quot;Regs_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.regservicebuilder.model.impl.FarmerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.regservicebuilder.model.impl.FarmerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Farmer
 * @see com.example.regservicebuilder.model.impl.FarmerImpl
 * @see com.example.regservicebuilder.model.impl.FarmerModelImpl
 * @generated
 */
public interface FarmerModel extends BaseModel<Farmer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a farmer model instance should use the {@link Farmer} interface instead.
     */

    /**
     * Returns the primary key of this farmer.
     *
     * @return the primary key of this farmer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this farmer.
     *
     * @param primaryKey the primary key of this farmer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the farmer ID of this farmer.
     *
     * @return the farmer ID of this farmer
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this farmer.
     *
     * @param farmerId the farmer ID of this farmer
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the organization name of this farmer.
     *
     * @return the organization name of this farmer
     */
    @AutoEscape
    public String getOrganizationName();

    /**
     * Sets the organization name of this farmer.
     *
     * @param organizationName the organization name of this farmer
     */
    public void setOrganizationName(String organizationName);

    /**
     * Returns the legal form of this farmer.
     *
     * @return the legal form of this farmer
     */
    @AutoEscape
    public String getLegalForm();

    /**
     * Sets the legal form of this farmer.
     *
     * @param legalForm the legal form of this farmer
     */
    public void setLegalForm(String legalForm);

    /**
     * Returns the inn of this farmer.
     *
     * @return the inn of this farmer
     */
    @AutoEscape
    public String getInn();

    /**
     * Sets the inn of this farmer.
     *
     * @param inn the inn of this farmer
     */
    public void setInn(String inn);

    /**
     * Returns the kpp of this farmer.
     *
     * @return the kpp of this farmer
     */
    @AutoEscape
    public String getKpp();

    /**
     * Sets the kpp of this farmer.
     *
     * @param kpp the kpp of this farmer
     */
    public void setKpp(String kpp);

    /**
     * Returns the ogrn of this farmer.
     *
     * @return the ogrn of this farmer
     */
    @AutoEscape
    public String getOgrn();

    /**
     * Sets the ogrn of this farmer.
     *
     * @param ogrn the ogrn of this farmer
     */
    public void setOgrn(String ogrn);

    /**
     * Returns the district ID of this farmer.
     *
     * @return the district ID of this farmer
     */
    public long getDistrictId();

    /**
     * Sets the district ID of this farmer.
     *
     * @param districtId the district ID of this farmer
     */
    public void setDistrictId(long districtId);

    /**
     * Returns the registration date of this farmer.
     *
     * @return the registration date of this farmer
     */
    public Date getRegistrationDate();

    /**
     * Sets the registration date of this farmer.
     *
     * @param registrationDate the registration date of this farmer
     */
    public void setRegistrationDate(Date registrationDate);

    /**
     * Returns the archived of this farmer.
     *
     * @return the archived of this farmer
     */
    @AutoEscape
    public String getArchived();

    /**
     * Sets the archived of this farmer.
     *
     * @param archived the archived of this farmer
     */
    public void setArchived(String archived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.regservicebuilder.model.Farmer farmer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.regservicebuilder.model.Farmer> toCacheModel();

    @Override
    public com.example.regservicebuilder.model.Farmer toEscapedModel();

    @Override
    public com.example.regservicebuilder.model.Farmer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
